### ISSUE TITLE
(Tracking) - Refactor tasks and utilities

### ISSUE THREAD

**Issue by TheDonDope** [mgechev/angular2-seed#956]
Based on the last comments in #850, this issue will provide basic information and lists task that need to be done to solve the problem.

**Current situation:**
With https://github.com/mgechev/angular2-seed/pull/894 being merged, we now have the ability to make use of custom plugin configuration. This is already done now for SystemJS (https://github.com/brian428/angular2-seed/blob/ad90fee764748c8151f5c09cecf33cfd0fa56ecb/tools/utils/seed/code_change_tools.ts#L10). 

As @brian428 commented in #850 :

>  But there are probably numerous other places where using getPluginConfig() could/should be called.

So i propose we take a look at this.

For me this would also mean a chance of some general refactoring of the tasks. We already took some action here, by adding more documentation, so in the process of migrating to the usage of `getPluginConfig`) we could do some general cleanup while we are at it. For example: 

- [ ] Get a list of plugins that could make use of `getPluginConfig`
- [ ] Review all existing tasks, looking for extractable reusable utility code (not everyone should need to do a `import 'join' from { path }`)
- [ ] Create Utilities / Base Tasks classes and align the current tasks to follow the same schema / pattern (providing for more easy to add new / enhance existing tasks)
- [ ] Follow up with #927 and prepare for necessary changes

That is my initial thought dump on that topic, discussion is opened !

**Comment by ludohenin** [comment]
> (providing for more easy to add new / enhance existing tasks)

Do you think it is hard ?
We should be doing too much black magic.

**Comment by TheDonDope** [comment]
Hey! I can't think of one particular "too hard" task to modify right now. I just remembered when i added the inline documentation to the `tools` section, that a lot of the code i saw was built similar, with a few exceptions. 
Truly, i do **not** want to propose to absolutely over-engineer the stuff, just some house-keeping (maybe also tackle those `TODO` and `FIXME` tags).

**Comment by mgechev** [comment]
At this point I don't think we can encapsulate any general functionality within an base task. Reviewing and inspecting the current set of tasks may overturn this.

I guess this issue is mostly related to research/design, rather than concrete idea for refactoring/implementation.

**Comment by mgechev** [comment]
@TheDonDope are you still planning to do research in this direction or we can close the issue?

**Comment by TheDonDope** [comment]
@mgechev Sorry, i haven't had time for any research here, we can close it for now, i would only open it up again once i actually get around to looking into it more deeply!
